[global]
developmentMode = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxUploadSize = 50
